---
title: "1-3-0_retrieve_barcodes_for_UMITools"
output: html_document
date: "2025-04-10"
---

```{r}
library(Seurat)
library(data.table)
library(tidyverse)
```

```{r}
RDSdir <- "RDS/"
outdir <- "individual_barcodes/"
if (!dir.exists(outdir)) dir.create(outdir)
```


```{r}
whole <- readRDS(paste0(RDSdir,"whole_integrated_wTCR_woUD_V1p5.Rds"))
```

```{r}
meta <- whole@meta.data
```

```{r}
head(meta$barcode)
```


```{r}
meta$barcode <- unlist(lapply(meta$barcode, function(x){unlist(strsplit(x,split = "_"))[3]}))
head(meta$barcode)
```


```{r}
table(meta$patient_id,meta$stage)
```
export barcode.txt for each patient with stage information

```{r}
stages <- c("Early","Mid","Late")
for (s in stages){
  sample_meta <- meta %>% filter(stage == s)
  patient_ids <- unique(sample_meta$patient_id)
  for (p in patient_ids){
    patiend.bc <- sample_meta$barcode[sample_meta$patient_id == p]
    write.table(patiend.bc,file = paste0(outdir,"barcodes_",s,"_",p,".txt"),sep = "\t", quote = F, col.names = F,row.names = F)
  }
}
```

